### ISSUE TITLE
Add instructions for updating firmware

### ISSUE THREAD

**Issue by jmickelin** [intechstudio/knot#10]
There doesn't seem to be any clear instructions for updating the firmware, either here on Github or on the retail page. The latter has a link called "Firmware update" on https://docs.intech.studio/, but it takes you to a page describing firmware updates only for the Grid controllers. 

One _could_ deduce that updating works similarly on the Knot as the instructions under the "Updating the firmware manually" section on the Grid page (holding the mode button while connecting the USB-C port to a computer makes the Knot present itself as a USB mass storage device, to which you copy the `.uf2` file, and then unmount the device to perform the installation). This is not at all obvious, however, especially since the Grid page starts by describing a different update method which does not seem at all applicable to the Knot, so most users would click away from the page right away. The only hint about firmware updates being possible at all is a single sentence in the bullet point list of the Knot's features (`"• Mode button for updating the firmware"`), and the fact that there are Releases of `.uf2` files on the Github repo.

Much clearer would be to have a dedicated page for the Knot's firmware update instruction as well, even if the steps described end up being identical as for the Grid.

The Grid firmware update page also contains warnings about making sure to select the firmware corresponding to the correct microcontroller by reading the `INFO_UF2.TXT` file on the mass storage device and choosing the correct binary. This does not seem to be applicable to the Knot, since the firmware release only has one flavour of binary (corresponding to the ESP32) and would probably not need to be present on the Knot firmware update page. However, for the sake of clarity and consistency, the filename for the firmware should be renamed to make it explicit that it is for the ESP32 board, using the same naming scheme as the Grid's firmware releases. For instance: `knot_esp32_release_2023-07-18-1139.uf2`. This removes one extra layer of doubt for users and serves as a slight sanity check before the "here-goes-nothing" moment when doing the update.

**Comment by SukuWc** [comment]
Thanks for the feedback I fixed the naming of the .uf2 file. I will also forward this issue to website and documentation teams! @narayb
