### ISSUE TITLE
Voltage for DC-in?

### ISSUE THREAD

**Issue by giacecco** [intechstudio/knot#5]
At the back of the Knot, it says `6-15V DC`. It looks like it could take anything _between_ 6 and 15, but in reality, it wants exactly 6 or 15. I tried with a 9V I use with my pedal and the Knot did not turn on. Please change the label to `6V or 15V DC`.

I have made a pull requests to update the website accordingly, too.

**Comment by SukuWc** [comment]
What polarity is the 9V power supply? Early on knot units the automatic polarity detection was not working correctly, so if the power supply is center negative variant (typically used by guitar pedals) then that could be the problem!
