### ISSUE TITLE
FW Update = Pulsing white LED's

### ISSUE THREAD

**Issue by lucasfackler** [intechstudio/knot#8]
After dropping the latest release .UF2 onto the disk, Knot reboots and now LED's are white and pulse slowly.
What does this mean? No MIDI either.

**Comment by SukuWc** [comment]
That means that knot is waiting for a MIDI controller to be connected! What midi controller are you trying to connect?

**Comment by narayb** [comment]
We have solved this issue a while back, you can close it if that's alright with you.
