### ISSUE TITLE
Feature request: let Knot remember the Mode setting

### ISSUE THREAD

**Issue by narayb** [intechstudio/knot#9]
In certain workflows users would use the Blue Mode with MIDI Through/Merge exclusively, but at the moment this requires setting the Mode after each power cycle.

It would be preferable if Knot could remember the last Mode set until the next boot.

**Comment by mulkeybe** [comment]
This would be a very useful feature. I run an external Midi clock into my knot and merge it with Grid controller MIDI data stream. It would be nice if knot would remember the mode so I wouldn’t have to press the utility button every time that I power up my system

**Comment by narayb** [comment]
This is a work in progress feature, more news soon!

**Comment by kkerti** [comment]
<img width="559" alt="image" src="https://github.com/intechstudio/knot/assets/47832952/5e5bd658-0df5-43de-b368-86a2dbde7c1d">
Please let me (or users on the discord community channel) know if we have an ETA for this.

**Comment by SukuWc** [comment]
Feature implemented, fix coming soon in firmware version v1.0.3
